pipeline:
  publish:
    image: docker
    secrets: [docker_username,docker_password]
    commands:
        - docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD registry-vpc.cn-shenzhen.aliyuncs.com/pipipan/frontend
        - docker build --no-cache -t registry-vpc.cn-shenzhen.aliyuncs.com/pipipan/frontend:master -f Dockerfile .
        - docker push registry-vpc.cn-shenzhen.aliyuncs.com/pipipan/frontend:master
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    when:
        branch: master
        status: success

  deploy:
    image: appleboy/drone-ssh
    host: 202.120.40.8
    secrets: [ssh_username, ssh_password]
    port: 30250
    script:
      - /root/shell/deployment-wjs.sh frontend 30258 8080
